import { ActionRegistryItem } from '../command-palette';
import { NavKey } from '../nav';

export function createGotoActions(onNavigate: (key: NavKey) => void): ActionRegistryItem[] {
  const actions: ActionRegistryItem[] = [
    {
      id: 'goto-mission-control',
      verb: 'Go to',
      noun: 'Mission Control',
      description: 'Overview dashboard',
      icon: '🎯',
      scope: 'global',
      handler: 'navigate',
      keywords: ['dashboard', 'home', 'overview', 'main'],
    },
    {
      id: 'goto-memory-vault',
      verb: 'Go to',
      noun: 'Memory Vault',
      description: 'Memory and knowledge management',
      icon: '🧠',
      scope: 'global',
      handler: 'navigate',
      keywords: ['memory', 'vault', 'knowledge', 'notes'],
    },
    {
      id: 'goto-vault-health',
      verb: 'Go to',
      noun: 'Vault Health',
      description: 'Memory vault health monitoring',
      icon: '❤️',
      scope: 'global',
      handler: 'navigate',
      keywords: ['health', 'vault', 'status', 'monitoring'],
    },
    {
      id: 'goto-insights',
      verb: 'Go to',
      noun: 'Insights',
      description: 'Analytics and insights',
      icon: '💡',
      scope: 'global',
      handler: 'navigate',
      keywords: ['analytics', 'insights', 'reports', 'data'],
    },
    {
      id: 'goto-approvals',
      verb: 'Go to',
      noun: 'Approvals',
      description: 'Pending approvals queue',
      icon: '✅',
      scope: 'global',
      handler: 'navigate',
      keywords: ['approvals', 'pending', 'queue', 'review'],
    },
    {
      id: 'goto-automations',
      verb: 'Go to',
      noun: 'Automations',
      description: 'Workflow operations',
      icon: 'A',
      scope: 'global',
      handler: 'navigate',
      keywords: ['automations', 'workflows', 'triggers', 'actions'],
    },
    {
      id: 'goto-issues',
      verb: 'Go to',
      noun: 'Issues',
      description: 'Issue editor and assignments',
      icon: 'I',
      scope: 'global',
      handler: 'navigate',
      keywords: ['issues', 'work', 'assignment', 'production', 'testing'],
    },
    {
      id: 'goto-review-queue',
      verb: 'Go to',
      noun: 'Review Queue',
      description: 'Verify work that is ready for approval',
      icon: 'R',
      scope: 'global',
      handler: 'navigate',
      keywords: ['review', 'queue', 'approve', 'verify', 'done'],
    },
    {
      id: 'goto-triage-queue',
      verb: 'Go to',
      noun: 'Triage Queue',
      description: 'Issue triage and management',
      icon: '📋',
      scope: 'global',
      handler: 'navigate',
      keywords: ['triage', 'queue', 'issues', 'management'],
    },
    {
      id: 'goto-agents',
      verb: 'Go to',
      noun: 'Agents',
      description: 'Agent management and configuration',
      icon: '🤖',
      scope: 'global',
      handler: 'navigate',
      keywords: ['agents', 'bots', 'ai', 'configuration'],
    },
    {
      id: 'goto-rule-packs',
      verb: 'Go to',
      noun: 'Rule Packs',
      description: 'Policy rule packs management',
      icon: '📋',
      scope: 'global',
      handler: 'navigate',
      keywords: ['rules', 'policies', 'packs', 'compliance'],
    },
    {
      id: 'goto-scanner',
      verb: 'Go to',
      noun: 'Scanner',
      description: 'Security and compliance scanner',
      icon: '🔍',
      scope: 'global',
      handler: 'navigate',
      keywords: ['scanner', 'security', 'compliance', 'scan'],
    },
    {
      id: 'goto-process-health',
      verb: 'Go to',
      noun: 'Process Health',
      description: 'System process health monitoring',
      icon: '📊',
      scope: 'global',
      handler: 'navigate',
      keywords: ['health', 'processes', 'monitoring', 'status'],
    },
    {
      id: 'goto-activity',
      verb: 'Go to',
      noun: 'Activity Log',
      description: 'System activity and events',
      icon: '📈',
      scope: 'global',
      handler: 'navigate',
      keywords: ['activity', 'log', 'events', 'history'],
    },
    {
      id: 'goto-evidence',
      verb: 'Go to',
      noun: 'Evidence Report',
      description: 'Compliance evidence and reports',
      icon: '📄',
      scope: 'global',
      handler: 'navigate',
      keywords: ['evidence', 'reports', 'compliance', 'audit'],
    },
    {
      id: 'goto-autopilot',
      verb: 'Go to',
      noun: 'Autopilot',
      description: 'Autonomous operations',
      icon: '🛩️',
      scope: 'global',
      handler: 'navigate',
      keywords: ['autopilot', 'autonomous', 'auto', 'operations'],
    },
    {
      id: 'goto-map',
      verb: 'Go to',
      noun: 'Map',
      description: 'System topology map',
      icon: '🗺️',
      scope: 'global',
      handler: 'navigate',
      keywords: ['map', 'topology', 'network', 'diagram'],
    },
    {
      id: 'goto-settings',
      verb: 'Go to',
      noun: 'Settings',
      description: 'System configuration and preferences',
      icon: '⚙️',
      scope: 'global',
      handler: 'navigate',
      keywords: ['settings', 'configuration', 'preferences', 'config'],
    },
  ];

  // Add navigation handlers to each action
  return actions.map(action => ({
    ...action,
    handler: () => {
      const navKey = action.id.replace('goto-', '') as NavKey;
      onNavigate(navKey);
    },
  }));
}
