/**
 * Evidence report signing — HMAC-SHA256 PDF trailer + hash chain.
 *
 * Every PDF stored in evidence_reports gets a SHA-256 hash computed over the
 * raw bytes and appended as a JSON trailer on a new line after %%EOF.  The
 * daemon's HMAC key lives under <dataDir>/keys/evidence-report.key, and the
 * same directory must be passed to both signPdf and verifyPdfSignature so
 * they agree on where the key lives.  Hash chain validation uses the audit
 * hash stored in each policy_decisions row; report-level signing is separate
 * — it proves the PDF was generated by this daemon and hasn't been tampered
 * with since.
 *
 * Format of the appended trailer (the hmac travels inside the PDF so a
 * standalone file is self-verifiable, not just the DB row):
 *   %%EOF\n<!--sig-->{"alg":"HS256","pdfHash":"<sha256 hex>","reportId":"<id>","ts":"<iso ts>","keyId":"<id>","hmac":"<hex>"}<!--sig-->\n
 * The <!--sig--> markers let us parse the trailer back out without parsing the
 * full PDF structure.  The hmac covers the canonical serialization of
 * {alg,pdfHash,reportId,ts,keyId} (computed before hmac is added — no
 * chicken-and-egg).  Verification recomputes the content hash from the bytes
 * before the trailer, then recomputes the hmac over the same canonical
 * serialization and compares against the embedded hmac field.
 */

import { createHash, createHmac } from "node:crypto";
import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { join } from "node:path";

const KEY_FILENAME = "evidence-report.key";
const TRAILER_MARKER = "<!--sig-->";
const TRAILER_END_MARKER = "<!--sig-->";
const KEY_VERSION = 2;

/**
 * Compromised key IDs. A signing key with this id was committed to public
 * git history before redaction; treat any signature claiming this keyId as
 * forged and reject it at verify time. Append-only — never remove an entry,
 * only add new revocations.
 */
export const REVOKED_KEY_IDS: ReadonlySet<string> = new Set([
  "bed588cd",
]);

export interface SignedPdfResult {
  pdfBytes: Buffer;
  pdfHash: string;
  hmac: string;
  signedAt: string;
}

export interface SignatureInfo {
  alg: "HS256";
  pdfHash: string;
  reportId: string;
  ts: string;
  /** Human-readable key identity for audit. */
  keyId: string;
}

/**
 * Append an HMAC-SHA256 integrity trailer to the PDF buffer.
 *
 * @param pdfBytes  Raw PDF bytes (before any trailer)
 * @param reportId  Stable report identifier (from evidence_reports.id)
 * @param keyDir    Directory containing data/keys/ (dataDir from config)
 * @param now       Injectable clock for tests
 */
export function signPdf(
  pdfBytes: Buffer,
  reportId: string,
  keyDir: string,
  now: () => Date = () => new Date(),
): SignedPdfResult {
  const key = loadOrCreateKey(keyDir);
  const pdfHash = createHash("sha256").update(pdfBytes).digest("hex");
  const ts = now().toISOString();

  const sig: SignatureInfo = {
    alg: "HS256",
    pdfHash,
    reportId,
    ts,
    keyId: key.keyId,
  };

  const hmac = computeHmac(sig, key.secret);
  const trailerBody: SignatureInfo & { hmac: string } = { ...sig, hmac };
  const trailer = `\n${TRAILER_MARKER}${JSON.stringify(trailerBody)}${TRAILER_END_MARKER}\n`;
  return {
    pdfBytes: Buffer.concat([pdfBytes, Buffer.from(trailer, "utf8")]),
    pdfHash,
    hmac,
    signedAt: ts,
  };
}

/**
 * Verify the HMAC trailer on a signed PDF buffer.
 *
 * @param pdfBytes  Signed PDF bytes (including the appended trailer)
 * @param keyDir    Directory containing the signing key. Must be the same
 *                  directory `signPdf` used for this PDF (dataDir from config).
 * Returns the parsed SignatureInfo if valid; throws if tampered.
 */
export function verifyPdfSignature(pdfBytes: Buffer, keyDir: string): SignatureInfo {
  const raw = extractTrailer(pdfBytes);
  const trailer = JSON.parse(raw) as SignatureInfo & { hmac: string };
  const { hmac, ...sig } = trailer;

  if (sig.alg !== "HS256") {
    throw new Error(`Unknown signature algorithm: ${sig.alg}`);
  }

  // Revocation must fire before the hash/HMAC checks (a forgery minted with
  // the leaked key could still pass both) and before key lookup (the keyDir
  // is irrelevant to this check).
  if (REVOKED_KEY_IDS.has(sig.keyId)) {
    throw new Error(`Signing key revoked: ${sig.keyId} (key was leaked; rotate)`);
  }

  const content = contentBeforeTrailer(pdfBytes);
  const recomputed = createHash("sha256").update(content).digest("hex");
  if (recomputed !== sig.pdfHash) {
    throw new Error(
      `PDF content hash mismatch: expected ${sig.pdfHash}, got ${recomputed}`,
    );
  }

  const key = loadKey(keyDir, sig.keyId);
  if (!key) throw new Error(`Signing key not found: ${sig.keyId}`);

  const expectedHmac = computeHmac(sig, key.secret);

  // Compare in constant time to avoid timing attacks
  if (!timingSafeEqual(Buffer.from(expectedHmac), Buffer.from(hmac))) {
    throw new Error("HMAC verification failed — trailer may have been tampered with");
  }

  return sig;
}

/**
 * Canonical serialization of the fields the HMAC covers, in a fixed key
 * order. Sign and verify MUST call this same function so the HMAC input is
 * byte-identical on both sides.
 */
function canonicalSignaturePayload(sig: SignatureInfo): string {
  return JSON.stringify({
    alg: sig.alg,
    pdfHash: sig.pdfHash,
    reportId: sig.reportId,
    ts: sig.ts,
    keyId: sig.keyId,
  });
}

function computeHmac(sig: SignatureInfo, secret: string): string {
  return createHmac("sha256", secret)
    .update(Buffer.from(canonicalSignaturePayload(sig), "utf8"))
    .digest("hex");
}

function extractTrailer(buf: Buffer): string {
  const marker = Buffer.from(TRAILER_MARKER, "utf8");
  const endMarker = Buffer.from(TRAILER_END_MARKER, "utf8");
  const idx = buf.indexOf(marker);
  const endIdx = buf.indexOf(endMarker, idx + marker.length);
  if (idx === -1 || endIdx === -1) {
    throw new Error("PDF has no signature trailer");
  }
  return buf.subarray(idx + marker.length, endIdx).toString("utf8");
}

/**
 * Locate the start of the appended trailer robustly (independent of the
 * trailer's JSON length) and return only the bytes before it, so the
 * recomputed content hash matches what signPdf hashed.
 */
function contentBeforeTrailer(pdfBytes: Buffer): Buffer {
  const marker = Buffer.from(`\n${TRAILER_MARKER}`, "utf8");
  const idx = pdfBytes.lastIndexOf(marker);
  if (idx === -1) {
    throw new Error("PDF has no signature trailer");
  }
  return pdfBytes.subarray(0, idx);
}

function timingSafeEqual(a: Buffer, b: Buffer): boolean {
  if (a.length !== b.length) return false;
  let diff = 0;
  for (let i = 0; i < a.length; i++) {
    diff |= a[i]! ^ b[i]!;
  }
  return diff === 0;
}

// ---------------------------------------------------------------------------
// Key management
// ---------------------------------------------------------------------------

interface KeyRecord {
  keyId: string;
  secret: string; // hex-encoded HMAC secret
  version: number;
  createdAt: string;
}

/**
 * Load the active signing key from keyDir, creating it if absent.
 * Key is stored as a newline-delimited JSON file (one line per key version).
 * The active key is the highest-version entry.
 */
export function loadOrCreateKey(keyDir: string): KeyRecord {
  mkdirSync(keyDir, { recursive: true });
  const keyPath = join(keyDir, KEY_FILENAME);

  const existing = existsSync(keyPath)
    ? readKeyFile(keyPath)
    : null;

  if (existing && existing.length > 0) {
    // Return the highest-version key
    return existing.reduce((latest, k) =>
      k.version > latest.version ? k : latest,
    );
  }

  // Generate a new key
  const secret = createHash("sha256")
    .update(createHash("sha256").update(Date.now().toString()).digest())
    .digest("hex");
  const keyId = createHash("sha256").update(secret.slice(0, 16)).digest("hex").slice(0, 8);
  const record: KeyRecord = {
    keyId,
    secret,
    version: KEY_VERSION,
    createdAt: new Date().toISOString(),
  };

  writeFileSync(keyPath, JSON.stringify(record) + "\n", {
    encoding: "utf8",
    flag: "a",
  });

  return record;
}

function loadKey(keyDir: string, keyId: string): KeyRecord | null {
  const entries = readAllKeys(keyDir);
  return entries.find((k) => k.keyId === keyId) ?? null;
}

function readAllKeys(keyDir: string): KeyRecord[] {
  // This is a singleton daemon, so we read the key file once at startup.
  // For multi-instance you'd use a proper KMS; v1 is single-daemon.
  try {
    return readKeyFile(join(keyDir, KEY_FILENAME));
  } catch {
    return [];
  }
}

function readKeyFile(path: string): KeyRecord[] {
  if (!existsSync(path)) return [];
  const content = readFileSync(path, "utf8");
  return content
    .trim()
    .split("\n")
    .filter(Boolean)
    .map((line) => JSON.parse(line) as KeyRecord);
}
